### PR TITLE
Fix for reset/panic overriding the user's stop

### LINKED ISSUE #86: Cannot stop simulator with program containing reset in tight loop
```
from microbit import *
import machine
import random

while True:
    num = random.randint(1, 7)
    display.show(num)
    sleep(10) # works ok for me with 20ms
    machine.reset()
```

It stops OK with 20ms of delay or if you remove machine.reset().

### PR DESCRIPTION
**Pull request by microbit-matt-hillsdon**
Switch to an enum to make the possible states easier to follow and so we can check we're in the default state before committing to a reset or panic.

Closes https://github.com/microbit-foundation/micropython-microbit-v2-simulator/issues/86

### CODE REVIEW

File: src/board/index.ts [hunk 1]
```diff
@@ -386,23 +421,36 @@ export class Board {
...
+        // Skip the stopped state.
+        break;
+      }
+      case StopKind.UserStop: /* Fall through */
+      case StopKind.Default: {
         this.displayStoppedState();
+        break;
+      }
+      default: {
+        throw new Error("Unknown stop action: " + this.stopKind);
```
Comment (microbit-matt-hillsdon) [inline src/board/index.ts]:
```suggestion
        throw new Error("Unknown stop kind: " + this.stopKind);
```

File: src/board/index.ts [hunk 2]
```diff
@@ -386,23 +421,36 @@ export class Board {
...
-    } else {
-      if (this.afterStopped) {
-        this.afterStopped();
-        this.afterStopped = undefined;
+    switch (this.stopKind) {
+      case StopKind.Panic: {
+        if (panicCode === undefined) {
+          throw new Error("Must be set");
+        }
+        this.displayPanic(panicCode!);
```
Comment (microbit-matt-hillsdon) [inline src/board/index.ts]:
```suggestion
        this.displayPanic(panicCode);
```

File: src/board/index.ts [hunk 3]
```diff
@@ -425,8 +473,7 @@ export class Board {
    * reset() in MicroPython code throws ResetError.
    */
   async reset(): Promise<void> {
-    const noChangeRestart = () => {};
-    this.stop(noChangeRestart);
+    this.stop(StopKind.Reset);
```
Comment (microbit-matt-hillsdon) [inline src/board/index.ts]: Not a new bug, but it feels like this should return the promise.

Somewhat academic as we'll do the restart by calling start in setTimeout but at least it wouldn't look broken.

Comment (microbit-matt-hillsdon) [reply src/board/index.ts]: c8c4d44bbd20bac4b496d68bcca7bf8a4859b486

**Comment by microbit-matt-hillsdon** [comment]
As this affects key functionality, I'll stand-up a branch of the V3 editor that uses the review branch from this PR so we can test the start/stop/reset functionality in that context.

**Comment by microbit-matt-hillsdon** [comment]
URL to embed: https://review-python-simulator.usermbit.org/user-stop-wins/simulator.html

V3 editor review branch using the above: https://review-python-editor-v3.microbit.org/user-stop-wins/

File: src/board/index.ts [hunk 4]
```diff
@@ -108,10 +132,19 @@ export class Board {
...
-   * If undefined, then when main finishes we stay stopped.
-   * Otherwise we perform the action then clear this field.
+   * Controls the action after the user program completes.
+   *
+   * Determined by a combination of user actions (stop, reset etc) and program actions.
    */
-  private afterStopped: (() => void) | undefined;
+  private stopKind: StopKind = StopKind.Default;
+  /**
+   * Timeout for a pending start call due to StopKind.Restart.
```
Comment (microbit-robert) [inline src/board/index.ts]:
```suggestion
   * Timeout for a pending start call due to StopKind.Reset.
```

**Review by microbit-robert — APPROVED** [review]
Minor typo in comment. Looks good and appears to fix the linked issue. No unintentional side effects observed.
