### PR TITLE
Fix audio bug on simulator soft reboot

### LINKED ISSUE #70: Simulator error on soft reboot
When using CTRL-C, CTRL-D (or just CTRL-D after program completion) in the simulator serial to restart a program running music/audio, an error occurs and the simulator ends up in a state between started and stopped. Example program below:

```
import music
music.play(['c', 'd', 'e', 'c'])
```

Error in console: TypeError: Cannot read properties of undefined (reading 'createOscillator').

Confused state:
image

Additional error messages for using `speech.say`:
image

### PR DESCRIPTION
**Pull request by microbit-robert**
Closes #70.

### CODE REVIEW

File: src/board/audio/index.ts [hunk 1]
```diff
@@ -138,13 +138,7 @@ export class Audio {
     }
   }
 
-  boardStopped() {
-    if (this.context) {
-      this.context.close();
-      this.context = undefined;
-      this.oscillator = undefined;
-    }
```
Comment (microbit-robert) [inline src/board/audio/index.ts:146]: Previously thrown away when the board was stopped, but not re-initialised on a soft reboot. This is now thrown away when `stop()` is called.

Comment (microbit-matt-hillsdon) [reply src/board/audio/index.ts:146]: Can this mean we keep playing sounds? Would it be better to close/reinit the audio?

Comment (microbit-robert) [reply src/board/audio/index.ts:146]: This doesn't appear to be the case. It may be safer, but we need to find a way to pass  `wrapped._microbit_hal_audio_ready_callback` and `wrapped._microbit_hal_audio_speech_ready_callback` into an init function that is called on a soft reboot.

Comment (microbit-matt-hillsdon) [reply src/board/audio/index.ts:146]: I'm fine with this approach if there aren't practical issues. It might be safer in other ways as the audio context creation will always tied to a user event so less likely to hit browser issues.
